matrix:
  include:
    - language: node_js
      node_js:
        - 11.11.0

    - language: objective-c
      osx_image: xcode9.4
      install:
        - bundle install
        - yarn install
      script:
        - fastlane beta
