matrix:
  include:
    - language: node_js
      node_js:
        - 11.11.0

    - language: objective-c
      osx_image: xcode11.3
      install:
        - bundle install
      script:
        - fastlane beta
