# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:ios)

before_all do
  ensure_git_branch(branch: 'fastlane')
  ensure_git_status_clean
  git_pull
end

platform :android do
  # Android Lanes
end

platform :ios do
  desc "Description of what the lane does"
  lane :prepare do
    # add actions here: https://docs.fastlane.tools/actions

    appicon(appicon_image_file: '../Assets/Deploy/AppIcon.png',
      appicon_devices: [:ipad, :iphone, :ios_marketing])
  
  end

  lane :test do
    js_unit
  end
end
