# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
  ensure_git_branch(branch: 'fastlane')
  # ensure_git_status_clean
  # git_pull
end

platform :android do
  desc 'Build the Android application.'
  private_lane :build do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
  end
end

platform :ios do
  desc "Description of what the lane does"
  lane :prepare do
    # add actions here: https://docs.fastlane.tools/actions

    appicon(appicon_image_file: '../Assets/Deploy/AppIcon.png',
      appicon_devices: [:ipad, :iphone, :ios_marketing])
  end

  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(app_identifier: 'com.youngern.playground.FinalFormReactNative', type: 'development', readonly: true)
    match(app_identifier: 'com.youngern.playground.FinalFormReactNative', type: 'appstore', readonly: true)
  end

  lane :test do
    js_unit
  end

  desc 'Build the iOS application.'
  # private_lane :build do
  #   certificates
  #   increment_build_number(xcodeproj: './FinalFormReactNative.xcodeproj')
  #   gym(scheme: 'FinalFormReactNative', workspace: './FinalFormReactNative.xcworkspace')
  # end

  desc 'Ship to Testflight.'
  lane :beta do
    sync_code_signing(type: "appstore")
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "FinalFormReactNative.xcodeproj"
    )
    build_app(scheme: 'FinalFormReactNative', workspace: 'FinalFormReactNative.xcworkspace')

    # Might want to do something else here
    upload_to_testflight
  end
end
